account/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views


app_name = "account"
urlpatterns = [
    path("sign-up/id", views.signup, name="signup"),  # register
    path("sign-up/key", views.signup_password, name="signup-pwd"),
    path("sign-in", views.signin, name="signin"),
    # path('logon', auth_views.LoginView.as_view()),
    path("<int:user_id>", views.profile, name="profile"),
    path("", views.profile, name="profile"),
    path("sign-out/request", views.signout_request, name="signout_request"),
    path("sign-out", views.signout, name="signout"),
    # re_path(r'^connection$', views.connect, name='connection'),
]

# re_path(r'^articles/(?P<tag>.+)', views.list_articles_by_tag),
# re_path(r'^articles/(?P<year>\d{4})/(?P<month>\d{2})', views.list_articles),

opynfact_web_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from django.conf import settings
from django.conf.urls import include, url  # For django versions before 2.0


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    # url(r'^$', include('product.urls')),
    path("", include("product.urls")),
    path("account/", include("account.urls")),
    path("zadmyn/", admin.site.urls),
    # re_path(r'^zadmyn/$', admin.site.urls)
    path("sentry-debug/", trigger_error),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

product/urls.py
from django.conf.urls import url
from django.urls import path, re_path

from . import views
from .views_b import research as views_research


app_name = "product"
urlpatterns = [
    # url(r'^index/$', views.index),
    # url(r'^home/$', views.index),
    path("", views.index, name="home"),
    # re_path(r'^result/$', views.result, name='result'),
    path("result/<str:user_query>", views_research.result, name="result"),
    path("favorite", views.favorite, name="favorite"),
    path("parse/favorite", views.parse_favorite, name="parse_favorite"),
    # url(r'^(?P<_product_id>[0-9]+)/$', views.product, name='info'),
    path(
        "product/<int:product_id>/from/<str:page_origin>", views.product, name="product"
    ),
    path(
        "product/<int:product_id>/from/<str:page_origin>/<str:product_id_origin>/<str:user_query>",
        views.product,
        name="product",
    ),
    # url(r'^notices/$', views.notice, name='notice'),
    path("notices", views.notice, name="notice"),
]

product/models.py
from django.db import models
from django.contrib.auth import get_user_model


class ZProduct(models.Model):
    code = models.BigIntegerField(
        "Code", primary_key=True, default=0, null=False, unique=True
    )
    brands = models.CharField("Marque", max_length=256, null=True)
    name = models.CharField("Nom", max_length=256)
    url = models.URLField("URL", null=True)
    stores = models.CharField("Stores", max_length=256, null=True)
    # category_hierarchy = models.IntegerField(null=True)
    nutrition_grades = models.CharField("Nutri-Score", max_length=1, null=True)
    nova_group = models.SmallIntegerField("Nova", null=True)
    nutrition_score_fr = models.SmallIntegerField("Nutrition score", null=True)
    nutrition_score_uk = models.SmallIntegerField("Nutrition score", null=True)
    nutrition_score_beverage = models.SmallIntegerField(
        "Nutrition score beverage", null=True
    )
    fat_100g = models.FloatField("Matières grasses / Lipides", null=True)
    saturated_fat_100g = models.FloatField("Acides gras saturés", null=True)
    sugars_100g = models.FloatField("Sucres", null=True)
    salt_100g = models.FloatField("Sel", null=True)
    unique_scans_n = models.SmallIntegerField("Popularité", null=True)
    created_t = models.BigIntegerField("Date de création", null=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    last_modified_t = models.BigIntegerField(
        "Date de mise à jour", null=False, default=0
    )
    # last_modified = models.DateTimeField(auto_now_add=True)
    update_t = models.DateTimeField(
        "Date d'enregistrement", auto_now_add=True, null=True
    )
    image_url = models.URLField("Image URL", null=True)

    categories = models.ManyToManyField(
        "ZCategory", through="ZCategory_Product", related_name="products", blank=True
    )
    searchers = models.ManyToManyField(
        get_user_model(), through="ZSearch", related_name="searches", blank=True
    )
    users = models.ManyToManyField(
        get_user_model(), through="ZFavorite", related_name="favorites", blank=True
    )
    alternatives = models.ManyToManyField(
        "self", related_name="substituted", symmetrical=False, blank=True
    )

    class Meta:
        # app_label = 'product'
        verbose_name = "Produit"
        verbose_name_plural = "Produits"
        # constraints = [
        #     models.UniqueConstraint(fields=['brands', 'name'], name='product_identifier_unique'),
        # ]

    def __str__(self):
        return "{} - {} - {}".format(self.code, self.brands, self.name)


class ZCategory(models.Model):
    identifier = models.CharField(max_length=256, primary_key=True, unique=True)
    label = models.CharField(max_length=256, null=True)

    def __str__(self):
        return "{} - {}".format(self.identifier, self.label)


class ZCategory_Product(models.Model):
    product = models.ForeignKey("ZProduct", on_delete=models.CASCADE)
    category = models.ForeignKey("ZCategory", on_delete=models.CASCADE)

    hierarchy_index = models.PositiveSmallIntegerField(default=0, null=False)
    date = models.DateTimeField(auto_now=True)

    # alternatives = models.ManyToManyField(ZFavorite, related_name='zsearches', blank=True)


class ZFavorite(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    favorite = models.ForeignKey("ZProduct", on_delete=models.CASCADE)
    # alternatives = models.ManyToManyField(ZFavorite, related_name='zsearches', blank=True)

    date = models.DateTimeField(auto_now=True)


class ZSearch(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    target = models.ForeignKey("ZProduct", on_delete=models.CASCADE)
    favorite_alternatives = models.ManyToManyField(
        ZFavorite, related_name="zsearches", blank=True
    )

    date = models.DateTimeField(auto_now=True)

product/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        label="Nom",
        max_length=100,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        required=True,
    )
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(attrs={"class": "form-control"}),
        required=True,
    )


class QueryForm(forms.Form):
    query = forms.CharField(
        label="Query",
        max_length=100,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        required=True,
    )


class FavoriteForm(forms.Form):
    code = forms.IntegerField(
        label="Code",
        min_value=0,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        # widget=forms.NumberInput(attrs={'class': 'form-control'}),
        required=True,
    )
    is_favorite = forms.BooleanField(
        label="Favorite state",
        widget=forms.CheckboxInput(attrs={"class": "form-control"}),
        required=False,
    )

product/views.py
import os, sys
import json

import logging


from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    HttpResponsePermanentRedirect,
)
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from .models import ZProduct, ZCategory, ZSearch, ZCategory_Product
from .forms import QueryForm, FavoriteForm


DIR_BASE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
print(DIR_BASE)
sys.path.append(DIR_BASE)
from zopynfacts import products

# sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))


# Get an instance of a logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


def index(request):
    # print(ZContact.objects.all())
    # ZContact.objects.filter(name="Mike")[-1])
    # message = "This is the home page, the user is {}".format(ZContact.objects.filter(name="mike")[0])

    # album = get_object_or_404(Album, pk=album_id)
    # artists = [artist.name for artist in album.artists.all()]
    # artists_name = " ".join(artists)

    # context = {
    #     'album_title': album.title,
    #     'artists_name': artists_name,
    #     'album_id': album.id,
    #     'thumbnail': album.picture
    # }

    context = {"page": "home"}
    user_query = ""
    response = None

    if request.method == "POST":
        # POST method

        form = QueryForm(request.POST)
        context["page"] = "result"
        context["query"] = user_query
        if form.is_valid():
            # Form is correct.
            # We can proceed to booking.
            user_query = request.POST.get("query")

            # return HttpResponseRedirect(reverse('product:result', args=[user_query]))
            response = redirect("product:result", user_query=user_query)

        else:  # [TODO]: is not necessary
            # Form data doesn't match the expected format.
            # Add errors to the template.
            context["errors"] = form.errors.items()
            print("Form error")
            response = render(request, "product/list.html", context)
    else:
        # GET method.

        response = render(request, "product/index.html", context)

    return response


@login_required()  # By default, use LOGIN_URL in settings
def favorite(request):

    product_lst = request.user.favorites.order_by("name")[:]

    context = {"page": "favorite"}
    context["product_lst"] = product_lst
    context["favorite_lst"] = product_lst

    return render(request, "product/list.html", context)


def product(
    request, product_id, page_origin=None, product_id_origin=None, user_query=None
):

    if request.user.is_authenticated:
        # Get user's favorite product
        favorite_lst = request.user.favorites.all()

    try:
        product = ZProduct.objects.get(code=int(product_id))
    except ZProduct.DoesNotExist:
        message = "Unkown product id"
    else:
        message = "This is the product #{}-{} description page".format(
            product_id, product.name
        )

    return render(request, "product/product.html", locals())


def parse_favorite(request):

    context = {}

    if request.method == "POST":

        code = int(request.POST.get("code"))
        favorite = request.POST.get("favorite")
        print(type(code), code)
        print(type(favorite), favorite)

        if favorite == "true":
            favorite = True
        else:
            favorite = False

        print(code)
        print(favorite)

        # Update or create favorite product into db
        user_mdl = get_user_model().objects.get(username=request.user.username)
        print(request.user)
        print(user_mdl)
        try:
            favorite_mdl = ZProduct.objects.get(code=int(code))
        except ZProduct.DoesNotExist:
            print("CRITICAL ERROR GETINNG FAVORITE PRODUCT")
        else:
            if favorite:
                user_mdl.favorites.add(favorite_mdl)
            else:
                user_mdl.favorites.remove(favorite_mdl)
            favorite = not favorite
            print(favorite)

        print(user_mdl.favorites.all())
        context = {"code": code, "favorite": favorite}

    return HttpResponse(json.dumps(context))


def notice(request):

    return render(request, "product/notice.html", locals())


#     id = int(album_id) # make sure we have an integer.
#     album = ALBUMS[id] # get the album with its id.
#     artists = " ".join([artist['name'] for artist in album['artists']]) # grab artists name and create a string out of it.
#     message = "Le nom de l'album est {}. Il a été écrit par {}".format(album['name'], artists)
#     return HttpResponse(message)


# def search(request):
#     query = request.GET.get('query')
#     if not query:
#         message = "Aucun artiste n'est demandé"
#     else:
#         albums = [
#             album for album in ALBUMS
#             if query in " ".join(artist['name'] for artist in album['artists'])
#         ]

#         if len(albums) == 0:
#             message = "Misère de misère, nous n'avons trouvé aucun résultat !"
#         else:
#             albums = ["<li>{}</li>".format(album['name']) for album in albums]
#             message = """
#                 Nous avons trouvé les albums correspondant à votre requête ! Les voici :
#                 <ul>
#                     {}
#                 </ul>
#             """.format("</li><li>".join(albums))

#     return HttpResponse(message)

product/templates/product/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pur Beurre</title>

    {% load static %}

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" type="text/css" href="{% static 'product/vendor/fontawesome-free/css/all.min.css' %}">

    <!-- Font Awesome Icons -->
    <link rel="shortcut icon" href="{% static 'product/img/logo_pur_beurre-favicon.png' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'product/img/logo_pur_beurre-favicon.png' %}" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="{% static 'product/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS - Includes Bootstrap -->
    <link rel="stylesheet" href="{% static 'product/css/creative.min.css' %}">
    <link rel="stylesheet" href="{% static 'product/css/zstyle.css' %}">
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'product/css/icons.css' %}" /> {% endcomment %}

</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
            {% if page == 'home' %}
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
            {% else %}
            <a class="navbar-brand js-scroll-trigger" href="{% url 'product:home' %}">
            {% endif %}
                <img id="zlogo" src="{% static 'product/img/logo_pur_beurre.png' %}" alt="Home Top"> Pur Beurre
                <!-- <img class="img-fluid" src="{% static 'product/img/logo_pur_beurre.svg' %}" alt=""> Pur Beurre -->
            </a>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto my-2 my-lg-0">

                  <li class="nav-item">{% include "product/query.html" %}</li>
                  <li class="nav-item">
                    {% if user.is_authenticated %}
                    {% comment %} <a id=profile_a class="nav-link js-scroll-trigger" href="{% url 'account:profile' user.id %}">Mon Compte {{ user.username }}</a> {% endcomment %}
                    <a id=profile_a class="nav-link js-scroll-trigger" href="{% url 'account:profile'%}" title="Compte">
                      <i class="fas fa-2x fa-user-circle mb-4"></i> {{ user.username }}</a>
                    {% else %}
                    <a id=signin_a class="nav-link js-scroll-trigger" href="{% url 'account:signin' %}" title="Connexion"><i class="fas fa-2x fa-sign-in-alt mb-4"></i></a>
                    {% endif %}
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a id=favorite_a class="nav-link js-scroll-trigger" href="{% url 'product:favorite' %}" title="Mes aliments">
                      <i class="fas fa-2x fa-carrot mb-4"></i></a></li>
                      {% comment %} <img id="zcarrot" src="{% static 'product/img/noun_Carrot_29691.png' %}" alt="Mes aliments"></a></li> {% endcomment %}
                  <li class="nav-item">
                    <a id=signout_a class="nav-link js-scroll-trigger" href="{% url 'account:signout_request' %}" title="Déconnexion">
                      <i class="fas fa-2x fa-sign-out-alt mb-4"></i></a></li>
                  {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block mastead %}
    <!-- Masthead -->
    <header class="masthead masthead_product">
      <div class="container h-50">
        <div class="row h-50 align-items-center justify-content-center text-center">
          {% block masthead_title %}{% endblock %}
        </div>
      </div>
    </header> 
    {% endblock %}     
    
    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="bg-light py-5">
        <div class="container">
          <div class="row">
            <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
              <div><a id=notice_a class="d-block" href="{% url 'product:notice' %}">Mentions légales</a></div>
            </div>
            <div class="col-lg-4 mr-auto text-center">
              <a id=contact_lnk class="d-block" href="{% url 'product:home' %}#contact">Contact</a>
            </div>
          </div>

          {% comment %} <div class="small text-center text-muted">Copyright &copy; 2019 - Start Bootstrap</div> {% endcomment %}
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'product/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'product/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'product/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'product/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'product/js/creative.min.js' %}"></script>

</body>

</html>

product/templates/product/favorite.html
<div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">{{ list_title }}
    </h2>
    <hr class="detail-separator">
</div>

product/templates/product/list.html
{% extends 'product/base.html' %}

{% load static %}

{% if page == 'result' %}
{% block mastead %}
<!-- Masthead -->
<header class="masthead masthead_list">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h2 class="text-uppercase text-white font-weight-bold">Recherche : {{ query }}</h2>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 col-md-6 align-self-baseline text-center">
        <div class="mt-5">
            {% comment %} <!-- <p class="text-white-75 font-weight-light mb-5">Start Bootstrap can help you build better websites using the Bootstrap framework! Just download a theme and start customizing, no strings attached!</p> --> {% endcomment %}
            {% comment %} <!-- <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a> --> {% endcomment %}
          <h4 class="h4 mb-2">
            {% if product_target.nutrition_grades == 'a' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-a.svg' %}" alt="{{ product_target.nutrition_grades }}">
            {% elif product_target.nutrition_grades == 'b' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-b.svg' %}" alt="{{ product_target.nutrition_grades }}">
            {% elif product_target.nutrition_grades == 'c' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-c.svg' %}" alt="{{ product_target.nutrition_grades }}">
            {% elif product_target.nutrition_grades == 'd' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-d.svg' %}" alt="{{ product_target.nutrition_grades }}">
            {% elif product_target.nutrition_grades == 'e' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-e.svg' %}" alt="{{ product_target.nutrition_grades }}">
            {% else %}<i class="fas fa-2x fa-globe text-primary mb-4"></i>
            {% endif %}
            
            {% if product_target.nova_group == 1 %}<img class="img-fluid" src="{% static 'product/img/nova-group-1.svg' %}" alt="{{ product_target.nova_group }}">
            {% elif product_target.nova_group == 2 %}<img class="img-fluid" src="{% static 'product/img/nova-group-2.svg' %}" alt="{{ product_target.nova_group }}">
            {% elif product_target.nova_group == 3 %}<img class="img-fluid" src="{% static 'product/img/nova-group-3.svg' %}" alt="{{ product_target.nova_group }}">
            {% elif product_target.nova_group == 4 %}<img class="img-fluid" src="{% static 'product/img/nova-group-4.svg' %}" alt="{{ product_target.nova_group }}">
            {% else %}<i class="fas fa-2x fa-globe text-primary mb-4"></i>                        
            {% endif %}
              {% comment %} - {{ product_target.unique_scans_n }} {% endcomment %}
          </h4>
          {% if product_target.image_url %}
          <p>
            <a class="portfolio-box" href="{% url 'product:product' product_target.code page product_target.code query %}">
              <img class="img-fluid" src={{ product_target.image_url }} alt="">
            </a>
          </p>
          {% else %}
          <i class="fas fa-4x fa-globe text-primary mb-4"></i>
          {% endif %}
          <h5 class="h5 mb-2">
          {% if user.is_authenticated %}
            <a id={{ product_target.code }} href="javascript:;" data-state="{% if product_target in favorite_lst %}false{% else %}true{% endif %}" onclick="set_favorite(this.id, this.getAttribute('data-state'))">
                {% if product_target in favorite_lst %}
                <i class="fas fa-1x fa-heart mb-4"></i>    {% comment %} fa-star {% endcomment %}
                {% else %}
                <i class="far fa-1x fa-heart mb-4"></i>
                {% endif %}
            </a>
            - 
          {% endif %}
          {% comment %} #{{ product_target.code }} -  {% endcomment %}
          {{ product_target.brands }}<br>{{ product_target.name }}
          </h5>
          {% comment %} <h6 class="h6 mb-2">[ {{ product_target.zcategory_product_set.hierarchy_index.0 }} ]</h6> {% endcomment %}
        </div>
      </div>
    </div>
  </div>
</header> 
{% endblock %}

{% elif page == 'favorite' %}

{% block masthead_title %}
<div class="col-lg-10 align-self-end">
  <h2 class="text-uppercase text-white font-weight-bold">Mes aliments</h2>
</div>  
{% endblock %}

{% endif %}

{% block content %}

{% if page == 'result' %}

  {% if query and product_target %}

  {% comment %}
  <ul>
    {% for category in product_target.categories.all %}
    <li>{{ category }}</li>
    {% endfor %}
  </ul>
  <p>Favorite</p>
  <ul>
    {% for favorite in favorite_lst %}
    <li>{{ favorite.code }} - {{ favorite.brands }} - {{ favorite.name }}</li>
    {% endfor %}
  </ul>
  {% endcomment %}

  {% comment %}
  <ul>
    {% for category in product_target.categories_tags %}
    <li>{{ category }}</li>
    {% endfor %}
  </ul>
  {% endcomment %}

  {% comment %}
  {% if product_target.compared_to_category %}
  <h6>[{{ product_target.compared_to_category }}]</h6>
  {% endif %}
  {% endcomment %}

  {% include 'product/result.html' with list_title='Produits de substitution' %}

  {% else %}
  <h2>Aucun produit de substitution trouvé pour "{{ query }}"</h2>
  {% endif %}

{% elif page == 'favorite' %}
{% include 'product/favorite.html' with list_title='Produits favoris' %}
{% else %}
{% include 'product/result.html' with list_title='Unknown Content' %}
{% endif %}

{% if errors %}
<div>
  {% for key, error in errors %}
  {% autoescape off %} {{ error }} {% endautoescape %}
  {% endfor %}
</div>
{% endif %}

<!-- List Section -->
<section id="product_section" class="page-section">
  <div class="container">

    {% if product_lst|length_is:"0" %}
    <h2 class="text-center mt-0">Nous n'avons trouvé aucun résultat à cette requête. Veuillez saisir une nouvelle.</h2>
    <hr class="divider my-4">
    <p class="text-muted text-center mb-0">Some BlaBlaBla.</p>

    {% else %}
    <div class="row">
      {% for product in product_lst %}
      <div class="col-lg-4 col-md-6 text-center">
        <div class="mt-5">
          <h4 class="h4 mb-2">
            {% if product.nutrition_grades == 'a' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-a.svg' %}" alt="">
            {% elif product.nutrition_grades == 'b' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-b.svg' %}" alt="">
            {% elif product.nutrition_grades == 'c' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-c.svg' %}" alt="">
            {% elif product.nutrition_grades == 'd' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-d.svg' %}" alt="">
            {% elif product.nutrition_grades == 'e' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-e.svg' %}" alt="">
            {% else %}<i class="fas fa-2x fa-globe text-primary mb-4"></i>
            {% endif %}
            
            {% if product.nova_group == 1 %}<img class="img-fluid" src="{% static 'product/img/nova-group-1.svg' %}" alt="">
            {% elif product.nova_group == 2 %}<img class="img-fluid" src="{% static 'product/img/nova-group-2.svg' %}" alt="">
            {% elif product.nova_group == 3 %}<img class="img-fluid" src="{% static 'product/img/nova-group-3.svg' %}" alt="">
            {% elif product.nova_group == 4 %}<img class="img-fluid" src="{% static 'product/img/nova-group-4.svg' %}" alt="">
            {% else %}<i class="fas fa-2x fa-globe text-primary mb-4"></i>
            {% endif %}
              {% comment %} - {{ product.unique_scans_n }} {% endcomment %}
          </h4>
          {% if product.image_url %}
          <p>
            {% if page == 'result' %}
            <a class="portfolio-box" href="{% url 'product:product' product.code page product_target.code query %}">
            {% else %}
            <a class="portfolio-box" href="{% url 'product:product' product.code page %}">
            {% endif %}
              <img class="img-fluid" src="{{ product.image_url }}" alt="">
            </a>
          </p>
          {% else %}
          <i class="fas fa-4x fa-globe text-primary mb-4"></i>
          {% endif %}
          <h5 class="h5 mb-2">
            {% if user.is_authenticated %}
            <a id={{ product.code }} href="javascript:;" data-state="{% if product in favorite_lst %}false{% else %}true{% endif %}" onclick="set_favorite(this.id, this.getAttribute('data-state'))">
                {% if product in favorite_lst %}
                <i class="fas fa-1x fa-heart mb-4"></i>    {% comment %} fa-star {% endcomment %}
                {% else %}
                <i class="far fa-1x fa-heart mb-4"></i>
                {% endif %}
            </a>
            - 
            {% endif %}
          {% comment %} #{{ product.code }} -  {% endcomment %}
          {{ product.brands }}<br>{{ product.name }}
          </h5>
          {% comment %} <h6 class="h6 mb-2">[ {{ product.zcategory_product_set.hierarchy_index.0 }} ]</h6> {% endcomment %}
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</section>

<script>
    var parse_favorite_url = "{% url 'product:parse_favorite' %}"
</script>
<script src="{% static 'product/js/zajax.js' %}"></script>
<script src="{% static 'product/js/zproduct.js' %}"></script>

{% endblock %}